#!/bin/sh

IMAGE=codercom/code-server:latest
NEW_IMAGE=ghcr.io/frost-tb-voo/code-server-rs
DIR=$(cd $(dirname ${BASH_SOURCE:-$0}); pwd)
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
cd ${DIR}/..
docker pull node:16-buster
docker pull ${IMAGE}
docker build -t ${NEW_IMAGE} \
 --build-arg VCS_REF=`git rev-parse --short HEAD` \
 --build-arg VSCODE_RUST_VERSION="0.7.8" \
 --build-arg RUST_ANALYZER_VERSION="2021-06-14" \
 --build-arg RUST_VERSION="1.52.1" \
 --build-arg RUSTUP_VERSION="1.24.1" \
 --build-arg rustArch="x86_64-unknown-linux-gnu" \
 --build-arg rustupSha256="fb3a7425e3f10d51f0480ac3cdb3e725977955b2ba21c9bdac35309563b115e8" \
 .
docker tag ${NEW_IMAGE} ${NEW_IMAGE}:local
docker images ${NEW_IMAGE}
